### 背景：
- 该项目主要为了加深对RFM模型的理解，案例数据是某企业从2015年到2018年共4年的用户订单抽样数据总共202827条数据，数据在Excel中包含5个sheet，前4个sheet以年份为单位存储为单个sheet中，最后一张会员等级表为用户的等级表
#### 主要针对4个字段进行展开分析：
- 会员ID
- 提交日期
- 订单号
- 订单金额

In [1]:
# 导包
import time
import numpy as np
import pandas as pd
import openpyxl
from sqlalchemy import create_engine

from pyecharts.charts import Bar3D
from pyecharts.commons.utils import JsCode
import pyecharts.options as opts

### 1. 加载数据

In [2]:
sheet_names = ['2015', '2016', '2017', '2018']
sheet_dict = pd.read_excel('./data/sales.xlsx', sheet_name=sheet_names)
sheet_dict

{'2015':               会员ID         订单号       提交日期    订单金额
 0      15278002468  3000304681 2015-01-01   499.0
 1      39236378972  3000305791 2015-01-01  2588.0
 2      38722039578  3000641787 2015-01-01   498.0
 3      11049640063  3000798913 2015-01-01  1572.0
 4      35038752292  3000821546 2015-01-01    10.1
 ...            ...         ...        ...     ...
 30769  39368100847  4281994827 2015-12-31   828.0
 30770       409757  4282010457 2015-12-31   199.0
 30771  38380526114  4282017675 2015-12-31   208.0
 30772     28074988  4282019440 2015-12-31    89.0
 30773  39460363230  4282025309 2015-12-31   719.0

 [30774 rows x 4 columns],
 '2016':               会员ID         订单号       提交日期     订单金额
 0      39288120141  4282025766 2016-01-01    76.00
 1      39293812118  4282037929 2016-01-01  7599.00
 2      27596340905  4282038740 2016-01-01   802.00
 3      15111475509  4282043819 2016-01-01    65.00
 4      38896594001  4282051044 2016-01-01    95.00
 ...            ...         ...        ...      ...
 41273  35336052906  4324910145 2016-12-31    99.00
 41274  39305835721  4324910148 2016-12-31   238.89
 41275  39296945352  4324910770 2016-12-31   765.00
 41276  14791026234  4324911025 2016-12-31    45.80
 41277  16779755770  4324911048 2016-12-31   119.00

 [41278 rows x 4 columns],
 '2017':               会员ID         订单号       提交日期    订单金额
 0      38765290840  4324911135 2017-01-01  1799.0
 1      39305832102  4324911213 2017-01-01   369.0
 2      34190994969  4324911251 2017-01-01   189.0
 3      38986333210  4324911283 2017-01-01   169.0
 4          4271359  4324911355 2017-01-01    78.0
 ...            ...         ...        ...     ...
 50834  39155833075  4338762307 2017-12-31    96.0
 50835  29523124076  4338762514 2017-12-31    99.0
 50836      7807573  4338762906 2017-12-31   258.0
 50837  36642530033  4338762958 2017-12-31   286.0
 50838  39155901156  4338763879 2017-12-31   249.0

 [50839 rows x 4 columns],
 '2018':               会员ID         订单号       提交日期    订单金额
 0      39229691808  4338764262 2018-01-01  3646.0
 1      39293668916  4338764363 2018-01-01  3999.0
 2      35059646224  4338764376 2018-01-01    10.1
 3          1084397  4338770013 2018-01-01   828.0
 4          3349915  4338770121 2018-01-01  3758.0
 ...            ...         ...        ...     ...
 81344  39229485704  4354225182 2018-12-31   249.0
 81345  39229021075  4354225188 2018-12-31    89.0
 81346  39288976750  4354230034 2018-12-31    48.5
 81347     26772630  4354230163 2018-12-31  3196.0
 81348  39455580335  4354235084 2018-12-31  2999.0

 [81349 rows x 4 columns]}

In [3]:
# 查询全部sheet页的信息，可初步查看是否有数据需要处理
for sheet_name in sheet_names:
    print(sheet_name)
    print(sheet_dict[sheet_name].info())
    print(sheet_dict[sheet_name].describe())

2015
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30774 entries, 0 to 30773
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    30774 non-null  int64
 1   订单号     30774 non-null  int64
 2   提交日期    30774 non-null  datetime64[ns]
 3   订单金额    30774 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 961.8 KB
None
               会员ID           订单号                           提交日期  \
count  3.077400e+04  3.077400e+04                          30774
mean   2.918779e+10  4.020414e+09  2015-07-01 20:55:49.424839168
min    2.670000e+02  3.000305e+09            2015-01-01 00:00:00
25%    1.944122e+10  3.885510e+09            2015-04-02 00:00:00
50%    3.746545e+10  4.117491e+09            2015-07-02 00:00:00
75%    3.923593e+10  4.234882e+09            2015-10-01 00:00:00
max    3.954613e+10  4.282025e+09            2015-12-31 00:00:00
std    1.385333e+10  2.630510e+08                            NaN

                订单金额
count   30774.000000
mean      960.991161
min         0.500000
25%        59.000000
50%       139.000000
75%       899.000000
max    111750.000000
std      2068.107231
2016
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41278 entries, 0 to 41277
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    41278 non-null  int64
 1   订单号     41278 non-null  int64
 2   提交日期    41278 non-null  datetime64[ns]
 3   订单金额    41277 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 1.3 MB
None
               会员ID           订单号                           提交日期  \
count  4.127800e+04  4.127800e+04                          41278
mean   2.908415e+10  4.313583e+09  2016-07-01 16:34:58.008624384
min    8.100000e+01  4.282026e+09            2016-01-01 00:00:00
25%    1.934990e+10  4.309457e+09            2016-04-01 00:00:00
50%    3.730339e+10  4.317545e+09            2016-07-02 00:00:00
75%    3.923182e+10  4.321132e+09            2016-10-01 00:00:00
max    3.954554e+10  4.324911e+09            2016-12-31 00:00:00
std    1.389468e+10  1.094572e+07                            NaN

                订单金额
count   41277.000000
mean      957.106694
min         0.100000
25%        59.000000
50%       147.000000
75%       888.000000
max    174900.000000
std      2478.560036
2017
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50839 entries, 0 to 50838
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    50839 non-null  int64
 1   订单号     50839 non-null  int64
 2   提交日期    50839 non-null  datetime64[ns]
 3   订单金额    50839 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 1.6 MB
None
               会员ID           订单号                           提交日期  \
count  5.083900e+04  5.083900e+04                          50839
mean   2.882368e+10  4.332466e+09  2017-07-02 00:53:06.530025984
min    2.780000e+02  4.324911e+09            2017-01-01 00:00:00
25%    1.869274e+10  4.328415e+09            2017-04-01 00:00:00
50%    3.688044e+10  4.331989e+09            2017-07-02 00:00:00
75%    3.923020e+10  4.337515e+09            2017-10-02 00:00:00
max    3.954554e+10  4.338764e+09            2017-12-31 00:00:00
std    1.409416e+10  4.404350e+06                            NaN

                订单金额
count   50839.000000
mean      963.587872
min         0.300000
25%        59.000000
50%       149.000000
75%       898.000000
max    123609.000000
std      2178.727261
2018
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81349 entries, 0 to 81348
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    81349 non-null  int64
 1   订单号     81349 non-null  int64
 2   提交日期    81349 non-null  datetime64[ns]
 3   订单金额    81348 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 2.5 MB
None
               会员ID           订单号                           提交日期  \
count  8.134900e+04  8.134900e+04                          81349
mean   2.902317e+10  4.348372e+09  2018-07-01 17:23:17.489827584
min    2.780000e+02  4.338764e+09            2018-01-01 00:00:00
25%    1.902755e+10  4.345654e+09            2018-04-01 00:00:00
50%    3.740121e+10  4.349448e+09            2018-07-01 00:00:00
75%    3.923380e+10  4.351639e+09            2018-10-01 00:00:00
max    3.954614e+10  4.354235e+09            2018-12-31 00:00:00
std    1.404116e+10  4.183774e+06                            NaN

                订单金额
count   81348.000000
mean      966.582792
min         0.000000
25%        60.000000
50%       149.000000
75%       899.000000
max    174900.000000
std      2204.969534

### 2. 数据预处理

In [4]:
# 遍历每一页并进行数据处理
for sheet_name in sheet_names:
    # 删除缺失值
    sheet_dict[sheet_name].dropna(inplace=True)
    # 过滤掉异常值（订单金额 < 1 的）
    sheet_dict[sheet_name] = sheet_dict[sheet_name][sheet_dict[sheet_name]['订单金额'] > 1]
    # 固定衡量的时间节点, 以每年的最后1天作为当年的分析节点，求出当年的最后一天并添加到新列
    sheet_dict[sheet_name]['max_year_date'] = sheet_dict[sheet_name]['提交日期'].max()

# 查看处理结果
for sheet_name in sheet_names:
    print(sheet_name)
    print(sheet_dict[sheet_name].info())
    print(sheet_dict[sheet_name].describe())

2015
<class 'pandas.core.frame.DataFrame'>
Index: 30574 entries, 0 to 30773
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           30574 non-null  int64
 1   订单号            30574 non-null  int64
 2   提交日期           30574 non-null  datetime64[ns]
 3   订单金额           30574 non-null  float64
 4   max_year_date  30574 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 1.4 MB
None
               会员ID           订单号                           提交日期  \
count  3.057400e+04  3.057400e+04                          30574
mean   2.921327e+10  4.020442e+09  2015-07-01 21:10:04.042650624
min    2.670000e+02  3.000305e+09            2015-01-01 00:00:00
25%    1.961657e+10  3.885746e+09            2015-04-02 00:00:00
50%    3.754532e+10  4.117491e+09            2015-07-02 00:00:00
75%    3.923630e+10  4.234853e+09            2015-10-01 00:00:00
max    3.954613e+10  4.282025e+09            2015-12-31 00:00:00
std    1.384598e+10  2.630518e+08                            NaN

                订单金额                  max_year_date
count   30574.000000                          30574
mean      967.270965  2015-12-30 23:59:59.999999744
min         1.500000            2015-12-31 00:00:00
25%        59.700000            2015-12-31 00:00:00
50%       142.000000            2015-12-31 00:00:00
75%       899.000000            2015-12-31 00:00:00
max    111750.000000            2015-12-31 00:00:00
std      2073.397861                            NaN
2016
<class 'pandas.core.frame.DataFrame'>
Index: 41001 entries, 0 to 41277
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           41001 non-null  int64
 1   订单号            41001 non-null  int64
 2   提交日期           41001 non-null  datetime64[ns]
 3   订单金额           41001 non-null  float64
 4   max_year_date  41001 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 1.9 MB
None
               会员ID           订单号                           提交日期  \
count  4.100100e+04  4.100100e+04                          41001
mean   2.910772e+10  4.313582e+09  2016-07-01 16:37:53.739664640
min    8.100000e+01  4.282026e+09            2016-01-01 00:00:00
25%    1.943201e+10  4.309457e+09            2016-04-01 00:00:00
50%    3.740237e+10  4.317545e+09            2016-07-02 00:00:00
75%    3.923184e+10  4.321133e+09            2016-10-01 00:00:00
max    3.954554e+10  4.324911e+09            2016-12-31 00:00:00
std    1.388571e+10  1.094832e+07                            NaN

                订单金额        max_year_date
count   41001.000000                41001
mean      963.542790  2016-12-31 00:00:00
min         1.500000  2016-12-31 00:00:00
25%        65.000000  2016-12-31 00:00:00
50%       149.000000  2016-12-31 00:00:00
75%       898.000000  2016-12-31 00:00:00
max    174900.000000  2016-12-31 00:00:00
std      2485.642632                  NaN
2017
<class 'pandas.core.frame.DataFrame'>
Index: 50451 entries, 0 to 50838
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           50451 non-null  int64
 1   订单号            50451 non-null  int64
 2   提交日期           50451 non-null  datetime64[ns]
 3   订单金额           50451 non-null  float64
 4   max_year_date  50451 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 2.3 MB
None
               会员ID           订单号                           提交日期  \
count  5.045100e+04  5.045100e+04                          50451
mean   2.884214e+10  4.332469e+09  2017-07-02 02:16:12.301837568
min    2.780000e+02  4.324911e+09            2017-01-01 00:00:00
25%    1.870549e+10  4.328416e+09            2017-04-01 00:00:00
50%    3.692362e+10  4.331989e+09            2017-07-02 00:00:00
75%    3.923070e+10  4.337528e+09            2017-10-02 00:00:00
max    3.954554e+10  4.338764e+09            2017-12-31 00:00:00
std    1.408666e+10  4.404894e+06                            NaN

                订单金额        max_year_date
count   50451.000000                50451
mean      970.990793  2017-12-31 00:00:00
min         1.500000  2017-12-31 00:00:00
25%        65.000000  2017-12-31 00:00:00
50%       155.000000  2017-12-31 00:00:00
75%       899.000000  2017-12-31 00:00:00
max    123609.000000  2017-12-31 00:00:00
std      2185.446995                  NaN
2018
<class 'pandas.core.frame.DataFrame'>
Index: 80801 entries, 0 to 81348
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           80801 non-null  int64
 1   订单号            80801 non-null  int64
 2   提交日期           80801 non-null  datetime64[ns]
 3   订单金额           80801 non-null  float64
 4   max_year_date  80801 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 3.7 MB
None
               会员ID           订单号                           提交日期  \
count  8.080100e+04  8.080100e+04                          80801
mean   2.905571e+10  4.348372e+09  2018-07-01 18:16:22.948230912
min    2.780000e+02  4.338764e+09            2018-01-01 00:00:00
25%    1.919622e+10  4.345654e+09            2018-04-01 00:00:00
50%    3.749326e+10  4.349448e+09            2018-07-01 00:00:00
75%    3.923398e+10  4.351641e+09            2018-10-02 00:00:00
max    3.954614e+10  4.354235e+09            2018-12-31 00:00:00
std    1.402185e+10  4.185250e+06                            NaN

                订单金额        max_year_date
count   80801.000000                80801
mean      973.119528  2018-12-31 00:00:00
min         1.500000  2018-12-31 00:00:00
25%        68.000000  2018-12-31 00:00:00
50%       151.700000  2018-12-31 00:00:00
75%       925.000000  2018-12-31 00:00:00
max    174900.000000  2018-12-31 00:00:00
std      2210.983968                  NaN

In [5]:
# 知识补充： 数据合并
# 1. 水平合并merge：可直接通过pd.merge(要合并的数据)
# 2. 垂直合并concat：要先把所有的数据项先转为list类型，再通过pd.concat(要合并的数据)

# 为了后续更方便对数据进行处理，这里把4个年份的数据进行合并为一个DataFrame，并重置索引
df_merge = pd.concat(list(sheet_dict.values()), ignore_index=True)
df_merge.info()
df_merge

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202827 entries, 0 to 202826
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   会员ID           202827 non-null  int64
 1   订单号            202827 non-null  int64
 2   提交日期           202827 non-null  datetime64[ns]
 3   订单金额           202827 non-null  float64
 4   max_year_date  202827 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 7.7 MB

               会员ID         订单号       提交日期    订单金额 max_year_date
0       15278002468  3000304681 2015-01-01   499.0    2015-12-31
1       39236378972  3000305791 2015-01-01  2588.0    2015-12-31
2       38722039578  3000641787 2015-01-01   498.0    2015-12-31
3       11049640063  3000798913 2015-01-01  1572.0    2015-12-31
4       35038752292  3000821546 2015-01-01    10.1    2015-12-31
...             ...         ...        ...     ...           ...
202822  39229485704  4354225182 2018-12-31   249.0    2018-12-31
202823  39229021075  4354225188 2018-12-31    89.0    2018-12-31
202824  39288976750  4354230034 2018-12-31    48.5    2018-12-31
202825     26772630  4354230163 2018-12-31  3196.0    2018-12-31
202826  39455580335  4354235084 2018-12-31  2999.0    2018-12-31

[202827 rows x 5 columns]

In [6]:
# 新增单独年份的列，方便后面做计算
df_merge["year"] = df_merge['提交日期'].dt.year
df_merge

               会员ID         订单号       提交日期    订单金额 max_year_date  year
0       15278002468  3000304681 2015-01-01   499.0    2015-12-31  2015
1       39236378972  3000305791 2015-01-01  2588.0    2015-12-31  2015
2       38722039578  3000641787 2015-01-01   498.0    2015-12-31  2015
3       11049640063  3000798913 2015-01-01  1572.0    2015-12-31  2015
4       35038752292  3000821546 2015-01-01    10.1    2015-12-31  2015
...             ...         ...        ...     ...           ...   ...
202822  39229485704  4354225182 2018-12-31   249.0    2018-12-31  2018
202823  39229021075  4354225188 2018-12-31    89.0    2018-12-31  2018
202824  39288976750  4354230034 2018-12-31    48.5    2018-12-31  2018
202825     26772630  4354230163 2018-12-31  3196.0    2018-12-31  2018
202826  39455580335  4354235084 2018-12-31  2999.0    2018-12-31  2018

[202827 rows x 6 columns]

In [7]:
# 计算用户最近一次购买时间间隔（当年年底 - 提交日期）
df_merge['date_interval'] = (df_merge['max_year_date'] - df_merge['提交日期']).dt.days
df_merge

,会员ID,订单号,提交日期,订单金额,max_year_date,year,date_interval
0,15278002468,3000304681,2015-01-01,499.0,2015-12-31,2015,364
1,39236378972,3000305791,2015-01-01,2588.0,2015-12-31,2015,364
2,38722039578,3000641787,2015-01-01,498.0,2015-12-31,2015,364
3,11049640063,3000798913,2015-01-01,1572.0,2015-12-31,2015,364
4,35038752292,3000821546,2015-01-01,10.1,2015-12-31,2015,364
...,...,...,...,...,...,...,...
202822,39229485704,4354225182,2018-12-31,249.0,2018-12-31,2018,0
202823,39229021075,4354225188,2018-12-31,89.0,2018-12-31,2018,0
202824,39288976750,4354230034,2018-12-31,48.5,2018-12-31,2018,0
202825,26772630,4354230163,2018-12-31,3196.0,2018-12-31,2018,0
202826,39455580335,4354235084,2018-12-31,2999.0,2018-12-31,2018,0

### 3. 分别计算RFM中的三个值

In [8]:
# 根据年和用户进行分组、统计
rfm_gb = df_merge.groupby(by=['year', '会员ID']).agg({
    'date_interval': 'min',   # r,取上面计算最近购买时间间隔的最小值
    '订单号': 'count',         # f
    '订单金额': 'sum'          # m
}).rename(columns={'date_interval': 'r', '订单号': 'f', '订单金额': 'm'}).reset_index()
rfm_gb

# 对R、F、M值分别通过分箱来打分，用的是3分法
# 分箱方式1：由系统通过bins的份数来自动分，但是出来的数据不够严谨，这里采用方式2
# rfm_gb['r_lable'] = pd.cut(rfm_gb['r'], bins=3, labels=['3', '2', '1'])
# rfm_gb['f_lable'] = pd.cut(rfm_gb['f'], bins=3, labels=['1', '2', '3'])
# rfm_gb['m_lable'] = pd.cut(rfm_gb['m'], bins=3, labels=['1', '2', '3'])
# rfm_gb

        year         会员ID    r  f       m
0       2015          267  197  2   105.0
1       2015          282  251  1    29.7
2       2015          283  340  1  5398.0
3       2015          343  300  1   118.0
4       2015          525   37  3   213.0
...      ...          ...  ... ..     ...
148586  2018  39538034299  272  1    49.0
148587  2018  39538034662  189  1  3558.0
148588  2018  39538035729  179  1  3699.0
148589  2018  39545237824  275  1    49.0
148590  2018  39546136285  163  1    19.9

[148591 rows x 5 columns]

In [9]:
# 分箱方式2：通过给定的自定义区间去分，这里这些区间我们依据于每项数据的分位数
# 先通过iloc[行，列]取出r、f、m三项数据以及描述性统计
rfm_gb.iloc[:, 2:].describe().T     # iloc[:, 2:]表示取所有行并截取从第二列开始到结束，iloc[行, 列]

      count         mean          std  min   25%    50%     75%       max
r  148591.0   165.524043   101.988472  0.0  79.0  156.0   255.0     365.0
f  148591.0     1.365002     2.626953  1.0   1.0    1.0     1.0     130.0
m  148591.0  1323.741329  3753.906883  1.5  69.0  189.0  1199.0  206251.8

### 4. 对RFM三个值进行分箱并进行打分

In [10]:
# 这里的bins区间取上面的 min、25%、75%、max 较为合理
# rfm_gb['r_label'] = pd.cut(rfm_gb['r'], bins=[-1, 79, 255, 365], labels=[3, 2, 1])
# rfm_gb['f_label'] = pd.cut(rfm_gb['f'], bins=[0, 2, 5, 130],labels=[1, 2, 3])  # 如果取bins=[0, 1, 1, 130]是不对的，这里的数据项特殊，需要结合业务部门沟通并制定区间范围
# rfm_gb['m_label'] = pd.cut(rfm_gb['m'], bins=[1, 69, 1199, 206252], labels=[1, 2, 3])
# rfm_gb
# 但是为了代码的健壮性，可以再扩展优化一下代码，代码可以灵活的不要写死，为此采用下面的写法

In [11]:
# 定义对应r、f、m对应的bins区间变量，假如之后要使用5分法进行处理，直接修改变量列表即可
r_bins = [-1, 79, 255, 365]
f_bins = [0, 2, 5, 130]
m_bins = [1, 69, 1199, 206252]

rfm_gb['r_label'] = pd.cut(rfm_gb['r'], bins=r_bins, labels=[i for i in range(len(r_bins) - 1, 0, -1)])
rfm_gb['f_label'] = pd.cut(rfm_gb['f'], bins=f_bins, labels=[i for i in range(1, len(f_bins))])
rfm_gb['m_label'] = pd.cut(rfm_gb['m'], bins=m_bins, labels=[i for i in range(1, len(m_bins))])
rfm_gb

        year         会员ID    r  f       m r_label f_label m_label
0       2015          267  197  2   105.0       2       1       2
1       2015          282  251  1    29.7       2       1       1
2       2015          283  340  1  5398.0       1       1       3
3       2015          343  300  1   118.0       1       1       2
4       2015          525   37  3   213.0       3       2       2
...      ...          ...  ... ..     ...     ...     ...     ...
148586  2018  39538034299  272  1    49.0       1       1       1
148587  2018  39538034662  189  1  3558.0       2       1       3
148588  2018  39538035729  179  1  3699.0       2       1       3
148589  2018  39545237824  275  1    49.0       1       1       1
148590  2018  39546136285  163  1    19.9       2       1       1

[148591 rows x 8 columns]

In [12]:
# 对RFM几个分数进行拼接
rfm_gb['r_label'] = rfm_gb['r_label'].astype(str)  # 先转换为字符串
rfm_gb['f_label'] = rfm_gb['f_label'].astype(str)
rfm_gb['m_label'] = rfm_gb['m_label'].astype(str)
rfm_gb['rfm_group'] = rfm_gb['r_label'] + rfm_gb['f_label'] + rfm_gb['m_label']
rfm_gb

        year         会员ID    r  f       m r_label f_label m_label rfm_group
0       2015          267  197  2   105.0       2       1       2       212
1       2015          282  251  1    29.7       2       1       1       211
2       2015          283  340  1  5398.0       1       1       3       113
3       2015          343  300  1   118.0       1       1       2       112
4       2015          525   37  3   213.0       3       2       2       322
...      ...          ...  ... ..     ...     ...     ...     ...       ...
148586  2018  39538034299  272  1    49.0       1       1       1       111
148587  2018  39538034662  189  1  3558.0       2       1       3       213
148588  2018  39538035729  179  1  3699.0       2       1       3       213
148589  2018  39545237824  275  1    49.0       1       1       1       111
148590  2018  39546136285  163  1    19.9       2       1       1       211

[148591 rows x 9 columns]

### 5. 导出结果（可选）
- 导出到Excel表格中
- 导出到数据库的表中

In [13]:
# 1. 导出结果到Excel文件中, 并忽略索引
# rfm_gb.to_excel('./data/sale_rfm_group.xlsx', index=False)

In [14]:
# 2. 导出到数据库的表中
# 1.创建数据库引擎对象
engine = create_engine('mysql+pymysql://root:123456@localhost:3306/rfm_db?charset=utf8')

# 2.导出数据到MySQL表中
# 参1: 存储结果的数据表名
# 参2: 引擎对象
# 参3: 忽略索引
# 参4: 如果表存在, 则替换数据
rfm_gb.to_sql('rfm_table', engine, index=False, if_exists='replace')

# 3.检查并查看数据
pd.read_sql('select * from rfm_table', engine)

### 6. RFM模型3D可视化
#### 数据准备：
- 三维坐标轴分别为：rfm_group(分组结果评分), year(统计年份), number(评分个数)

In [15]:
# 可视化的数据项都存放到display_data中，方便后面直接调用模块进行可视化
# 按拼接的总分和年份分组，统计每种用户群体类型的数量分布情况
display_data = rfm_gb.groupby([ 'rfm_group','year'], as_index=False).agg({'会员ID': 'count'}).rename(
    columns={'会员ID': 'number'}
)
display_data['rfm_group'] = display_data['rfm_group'].astype(int)
display_data

    rfm_group  year  number
0         111  2015    2180
1         111  2016    1498
2         111  2017    3169
3         111  2018    2271
4         112  2015    3811
..        ...   ...     ...
83        332  2018      24
84        333  2015      15
85        333  2016      28
86        333  2017      87
87        333  2018     355

[88 rows x 3 columns]

In [16]:
# 绘制图形
# 颜色池
range_color = ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf',
               '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']

range_max = int(display_data['number'].max())
c = (
    Bar3D()  #设置了一个3D柱形图对象
    .add(
        "",  #图例
        [d.tolist() for d in display_data.values],  #数据
        xaxis3d_opts=opts.Axis3DOpts(type_="category", name='RFM中用户类型'),  #x轴数据类型，名称，rfm_group
        yaxis3d_opts=opts.Axis3DOpts(type_="category", name='年份'),          #y轴数据类型，名称，year
        zaxis3d_opts=opts.Axis3DOpts(type_="value", name='对应用户类型数量'),   #z轴数据类型，名称，number
    )
    .set_global_opts(  # 全局设置
        visualmap_opts=opts.VisualMapOpts(max_=range_max, range_color=range_color),  #设置颜色，及不同取值对应的颜色
        title_opts=opts.TitleOpts(title="RFM模型中各类型用户分布情况"),   #设置标题
    )
)
c.render()  # 将结果渲染并保存到当前项目文件下的html文件中

'D:\\PythonProject\\SF_Study\\分析模型\\RFM\\render.html'